### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Maxmudjon** [chaeplin/homebridge-mqttdoor#1]
how to install on homebridge ?

**Comment by chaeplin** [comment]
check https://github.com/chaeplin/homebridge-plugin

**Comment by Maxmudjon** [comment]
thanks

**Comment by Maxmudjon** [comment]
npm ERR! enoent ENOENT: no such file or directory, open '/usr/lib/node_modules/https:/github.com/bertouttier/homebridge-mqttmotion.git'
npm ERR! enoent ENOENT: no such file or directory, open '/usr/lib/node_modules/https:/github.com/bertouttier/homebridge-mqttmotion.git'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/npm-debug.log
root@raspberrypi:/usr/lib/node_modules# npm install -g ./https://github.com/bertouttier/homebridge-mqttmotion.git
npm ERR! addLocal Could not install /usr/lib/node_modules/https:/github.com/bertouttier/homebridge-mqttmotion.git
npm ERR! Linux 4.4.32-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "./https://github.com/bertouttier/homebridge-mqttmotion.git"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /usr/lib/node_modules/https:/github.com/bertouttier/homebridge-mqttmotion.git
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/usr/lib/node_modules/https:/github.com/bertouttier/homebridge-mqttmotion.git'
npm ERR! enoent ENOENT: no such file or directory, open '/usr/lib/node_modules/https:/github.com/bertouttier/homebridge-mqttmotion.git'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/npm-debug.log

**Comment by chaeplin** [comment]
npm install -g ./xxxx : xxx is directory name og git cloned. npm install -g ./homebridge-mqttmotion
